services:
  medi-db:
    image: postgres:16-alpine
    container_name: medi-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: medi_db
    volumes:
      - medi-db-data:/var/lib/postgresql/data
    networks:
      - medi-net
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d medi_db" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

networks:
  medi-net:
    driver: bridge

volumes:
  medi-db-data:
  server-node-modules:
  server-logs:
  client-node-modules:
